#!/bin/bash
#
# Init file for interface_server daemon (E. Switzer)
# based on failnot init by Adam Hincks, Princeton, June 2006
#
# chkconfig: 2345 96 04
# description: interface_server hosts connections from ACT  \
#              hardware and clients
# config: /etc/ssh/sshd_config
# pidfile: /var/run/sshd.pid
# processname: interface_server

# source function library
. /etc/rc.d/init.d/functions

RETVAL=0
INTERFACE_SERVER=interface_server
INTERFACE_SERVER_BIN=/usr/sbin/call_$INTERFACE_SERVER
LOCKFILE=/var/lock/subsys/$INTERFACE_SERVER
PID_FILENAME=/var/run/$INTERFACE_SERVER.pid

start() {
  echo -n $"Starting $INTERFACE_SERVER: "
  daemon $INTERFACE_SERVER_BIN 
  RETVAL=$?
  [ "$RETVAL" = 0 ] && touch $LOCKFILE
  echo
}

stop() {
  echo -n $"Stopping $INTERFACE_SERVER: "
  if [ -n "`pidfileofproc $INTERFACE_SERVER`" ] ; then
    killproc $INTERFACE_SERVER -TERM
  else
    failure $"Stopping $INTERFACE_SERVER"
  fi
  RETVAL=$?
  [ "$RETVAL" = 0 ] && rm -f $LOCKFILE
  echo
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status $INTERFACE_SERVER
    RETVAL=$?
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart|status}"
    RETVAL=1
    ;;
esac

exit $RETVAL
