// Control database generated by make_controls python script.
// Version 'MBAC20080516152429'

// WARNING:    Do not edit this file!  It must be generated by the python script!

#include "control.h"

const char control_version[] = "MBAC20080516152429";

struct ctrl_cmd_param_t ctrl_cmd_param[] = {
  {"window_close", "input_select", "hkvar", "", 0, 1, 0, 11},
  {"point_mv_accel", "input_float", "hkpointing", "deg/s^2", 0, 100, 100, 159},
  {"dn_pgno_valid", "input_onoff", "hkdevicenet", "", 0, 1, 0.0, 150},
  {"dn_conf_mess", "input_onoff", "hkdevicenet", "", 0, 1, 0.0, 140},
  {"dn_stop_scan", "input_onoff", "hkdevicenet", "", 0, 1, 0.0, 144},
  {"point_az", "input_float", "hkpointing", "deg", -180, 180, 180.0, 156},
  {"dn_imm_stop", "input_onoff", "hkdevicenet", "", 0, 1, 0.0, 139},
  {"point_sec_mir_t", "input_float", "hkpointing", "mm", -8, 8, 0, 180},
  {"point_sec_fr_l", "input_float", "hkpointing", "mm", -9, 9, 0, 178},
  {"point_sec_mir_r", "input_float", "hkpointing", "mm", -8, 8, 0, 182},
  {"dn_newmsgack", "input_onoff", "hkdevicenet", "", 0, 1, 0.0, 154},
  {"dn_krdltrigger", "input_onoff", "hkdevicenet", "", 0, 1, 0.0, 149},
  {"point_scan_plus", "input_float", "hkpointing", "deg", 0, 10, 3, 161},
  {"dn_ext_start", "input_onoff", "hkdevicenet", "", 0, 1, 0.0, 141},
  {"dn_var_1_rdy", "input_onoff", "hkdevicenet", "", 0, 1, 0.0, 152},
  {"point_scan_minus", "input_float", "hkpointing", "deg", -10, 0, -3, 162},
  {"dn_recover", "input_select", "hkpointing", "", 0, 0, 0.0, 175},
  {"point_go_azel", "input_select", "hkpointing", "", 0, 0, 0.0, 160},
  {"dn_extend_pins", "input_onoff", "hkdevicenet", "", 0, 1, 0.0, 145},
  {"point_scan_num", "input_float", "hkpointing", "", 0, 1000000, 0.0, 165},
  {"dn_reset_all", "input_select", "hkpointing", "", 0, 0, 0.0, 155},
  {"dn_drives_off", "input_onoff", "hkdevicenet", "", 0, 1, 0.0, 143},
  {"snyc_framerate", "input_float", "hksnyc", "", 1, 4095, 150, 136},
  {"point_stop_motion", "input_select", "hkpointing", "", 0, 0, 0.0, 176},
  {"snyc_numrows", "input_float", "hksnyc", "", 1, 63, 41, 135},
  {"point_sec_fr_r", "input_float", "hkpointing", "mm", -9, 9, 0, 179},
  {"point_go_stow", "input_select", "hkpointing", "", 0, 0, 0.0, 173},
  {"dn_i_o_act", "input_onoff", "hkdevicenet", "", 0, 1, 1.0, 148},
  {"point_move_sec_zero", "input_select", "hkpointing", "", 0, 0, 0.0, 184},
  {"point_scan_accel", "input_float", "hkpointing", "deg/s^2", 0, 100, 100, 164},
  {"window_pow", "input_onoff", "hkabob", "", 0, 1, 0, 9},
  {"dn_heartbeat_enable", "input_onoff", "hkdevicenet", "", 0, 1, 0.0, 147},
  {"dn_retract_pins", "input_onoff", "hkdevicenet", "", 0, 1, 0.0, 146},
  {"window_open", "input_select", "hkvar", "", 0, 1, 0, 10},
  {"dn_drives_on", "input_onoff", "hkdevicenet", "", 0, 1, 0.0, 142},
  {"point_sec_mir_l", "input_float", "hkpointing", "mm", -8, 8, 0, 181},
  {"dn_down_seq", "input_select", "hkpointing", "", 0, 1, 0.0, 170},
  {"window_pol2", "input_onoff", "hkabob", "", 0, 1, 0, 8},
  {"window_pol1", "input_onoff", "hkabob", "", 0, 1, 0, 7},
  {"dn_var_2_rdy", "input_onoff", "hkdevicenet", "", 0, 1, 0.0, 153},
  {"snyc_manchout", "input_onoff", "hksnyc", "", 0, 1, 0.0, 138},
  {"point_move_sec", "input_select", "hkpointing", "", 0, 0, 0.0, 183},
  {"point_poll_motion", "input_select", "hkpointing", "", 0, 0, 0.0, 177},
  {"point_scan_start", "input_select", "hkpointing", "", 0, 0, 0.0, 167},
  {"dn_prog_parity", "input_onoff", "hkdevicenet", "", 0, 1, 0.0, 151},
  {"point_do_warm", "input_select", "hkpointing", "", 0, 0, 0.0, 171},
  {"point_mv_speed", "input_float", "hkpointing", "deg/s", 0, 100, 100, 158},
  {"point_el", "input_float", "hkpointing", "deg", 0, 60, 60, 157},
  {"dn_start_seq", "input_select", "hkpointing", "", 0, 1, 0.0, 169},
  {"snyc_framenum", "input_float", "hksnyc", "", 0, 4294967295L, 0.0, 137},
  {"point_track_start", "input_select", "hkpointing", "", 0, 0, 0.0, 168},
  {"snyc_rowlen", "input_float", "hksnyc", "", 1, 4095, 10, 134},
  {"point_go_maint", "input_select", "hkpointing", "", 0, 0, 0.0, 174},
  {"point_go_home", "input_select", "hkpointing", "", 0, 0, 0.0, 172},
  {"point_scan_secs", "input_float", "hkpointing", "", 0, 1000000, 0.0, 166},
  {"point_scan_speed", "input_float", "hkpointing", "deg/s", 0, 100, 100, 163},

  END_OF_CTRL_CMD_PARAM
};

char ctrl_sys[][16] = {
  "hkpointing",
  "hkdevicenet",
  "hkvar",
  "hkabob",
  "hksnyc",
  "hkbbc",

  END_OF_CTRL_SYS
};

